version: '3'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=epreschool_docker_v1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=epreschool123
    ports:
      - 54320:5432
    networks:
      - epreschoolnet

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: 'rabbitmqcontainer'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
    expose:
      - 5672
    networks:
      - epreschoolnet

  rabbitmq-service:
    build:
      context: .
      dockerfile: ePreschool.Subscriber\Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=appepreschool@gmail.com
      - SMTP_PASSWORD=jziu ueir unun gbtu
      - ENABLE_SSL=true
      - MAIL_TIMEOUT=10000
      - MAIL_FROM_ADDRESS=no-replay@ePreschool.ba
      - MAIL_DISPLAY_NAME=ePreschool.ba
    depends_on:
      - rabbitMQ
      - postgres
    networks:
      - epreschoolnet

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ePreschool.Api\Dockerfile
    environment:
      - ConnectionStrings:"User ID=postgres;Password=epreschool123;Server=postgres;Port=5432;Database=epreschool_docker_v1;Integrated Security=true;Pooling=true"
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=appepreschool@gmail.com
      - SMTP_PASSWORD="jziu ueir unun gbtu"
      - ENABLE_SSL=true
      - MAIL_TIMEOUT=10000
      - MAIL_FROM_ADDRESS=no-replay@ePreschool.ba
      - MAIL_DISPLAY_NAME=ePreschool.ba
    ports:
      - 8080:80
    networks:
      - epreschoolnet      
    depends_on:
      - postgres

networks:
  epreschoolnet:
    driver: bridge
