
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
 
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
 
FROM build AS publish
RUN dotnet publish "ePreschool.Subscriber\ePreschool.Subscriber.csproj" -c Release -o /app
FROM base AS final
WORKDIR /app
COPY --from=publish /app .
 
ENTRYPOINT ["dotnet", "ePreschool.Subscriber.dll"]